### PR TITLE
Patch for pageContext (#81)

### PR DESCRIPTION
**Pull request by zagaria**
Based on https://github.com/microsoft/azure-devops-extension-sdk/issues/81

### CODE REVIEW

**Comment by zagaria** [comment]
Hello.

@lohitakshgupta, @nkirchem did you have a chance to review?

**Review by andreygolubkow — APPROVED** [review]

**Comment by aminueza** [comment]
Hi, is there any update on this? I tested the code on my project and it solved the issue with getPageContext()

**Review by aminueza — APPROVED** [review]
LGTM! Tested the code and it could return the page context

**Comment by zagaria** [comment]
Closed due to https://github.com/microsoft/azure-devops-extension-sdk/pull/89

**Pull request closed without merging**
